AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - "data/**/*"
    - "vendor/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Exclude:
    - "test/**/*"

Naming/FileName:
  Exclude:
    - "lib/pl-zip-codes.rb"

Metrics/AbcSize:
  Max: 25
  Exclude:
    - "test/**/*"

Metrics/BlockLength:
  Exclude:
    - "test/**/*"
    - "**/*.rake"
